---
# playbook



- name: Configure Cisco NX-OS to RTR STIG
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Configure using role
      import_role:
        name: cisco-nexus-stig-role
