---
# tasks file for cisco-nexus-stig

#- name: Enable NX-API
#  hosts: ashburn-lab
#  gather_facts: no

- name: Enable NXAPI access with default configuration
  nxos_nxapi:
    state: present
    enable_http: yes
    enable_https: yes

- name: Set NTP Server
  when: ansible_network_os == 'nxos'
  loop: "{{ ntp_servers }}"
  nxos_config:
    lines:
      - ntp server {{ item }} use-vrf default

- name: "SV-221078r999687_rule: The Cisco switch must not be configured to have any feature enabled that calls home to the vendor"
  when: ansible_network_os == 'nxos'
  cisco.nxos.nxos_config:
    lines:
      - '  no enable'
    parents: callhome
    match: exact
    replace: line
