# DISA SRG:       SRG-NET-000205-RTR-000015
# Severity:       medium
# Rule ID:        SV-221095r999704_rule
# Identifiers:    SV-111009, V-101905, CCI-002403

- name: >
    [SV-221095r999704_rule] The Cisco perimeter switch must be configured to
    block all packets with any IP options
  cisco.nxos.nxos_config:
    lines:
      - no ip source-route
