---
# vars file for cisco-nexus-stig

ntp_servers:
  - 8.8.8.8

#
# The `stig_rules` variable is used to define the specific STIG rules
# that are being implemented in this role. Each key corresponds to a
# specific STIG rule, and the value is set to `true` to indicate that
# the rule is being enforced. This allows for easy reference and
# management of the STIG compliance within the role.
# The rules are identified by their unique identifiers, such as
# SRG_NET_000131_RTR_000083, or SRG_NET_000019_RTR_000007, which
# correspond to specific security requirements for network devices.
#
# By setting these rules to `true`, it indicates that the role is
# configured to comply with these security guidelines.
#
# This structure allows for clear documentation and
# management of compliance requirements within the Ansible role.
#
stig_rules:
  SRG_NET_000131_RTR_000083: true
  SRG_NET_000019_RTR_000007: true
  SRG_NET_000205_RTR_000015: true

#
# The `external_interfaces` variable is used to specify the interfaces
# that are considered external and should be configured accordingly.
# These interfaces are typically connected to external networks or devices,
# or commonly refered to as "uplink" interfaces.
#
external_interfaces:
  - Ethernet1/30
  - Ethernet1/31
  - Ethernet1/32
  - Ethernet1/14-17
